import type { Metadata } from 'next'

import { Kanit } from 'next/font/google'

import './globals.css'

const kanit = Kanit({ weight: '400', subsets: ['thai'] })

type Props = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = (props: Props) => {
  const { children } = props

  return (
    <html lang='en'>
      <body className={kanit.className}>{children}</body>
    </html>
  )
}

export default RootLayout
